#!groovy
/*
 * Copyright 2016 Testbirds GmbH
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

stage('PHP Tests') {
	dir('php/phpunit') {
		sh 'mkdir target'
		sh 'wget https://getcomposer.org/installer -O /proc/self/fd/1 | php'
		sh 'php composer.phar install --prefer-dist --optimize-autoloader'
		sh 'vendor/bin/phpunit test/SimpleExampleTest.php --log-junit target/junit.xml || true'
		sh 'vendor/bin/pdepend --jdepend-xml=target/jdepend.xml test/SimpleExampleTest.php || true'
		junit keepLongStdio: true, testResults: 'target/junit.xml'
		// junit keepLongStdio: true, testDataPublishers: [[$class: 'AttachmentPublisher'], [$class: 'StabilityTestDataPublisher']], testResults: 'target/junit.xml'
		// TODO: jdepend is not pipeline compatible
	}
}
